print("program nummer ett")
tal1=int(input("vad är det första talet? "))
tal2=int(input("vad är det andra talet? "))
print("summan av tal ett och två är", tal1+tal2)
print("produkten av tal ett och två är", tal1*tal2)

print("program 2.5")
fråga=str(input("har du en fråga?" ))
print("Astrid är dum och ful")

print("program nummer två")
basen=int(input("vad är basen i triangeln? "))
höjden=int(input("vad är höjden i triangeln? "))
print("triangelns area är:", (basen*höjden)/2)

print("program nummer tre (uppgift 3.5")
tankadvolym=float(input("hur många liter har du tankat?"))
Prisperliter=200
print("att betala:",tankadvolym*Prisperliter)
betalt=int(input("betala!"))
print("+–––––––––––––––––––––––––––––––––––––+")
print("|        KVITTO                       |")
print(f"|   tankad volym {tankadvolym}  liter    |")
print(f"|   pris per liter 200 kr {Prisperliter}        |")
print(f"|   betalt kronor {betalt}               |")
print("|                                       |")
print("|   Tack för besöktet och               |")
print("|   välkommen åter!                   |")
print("+–––––––––––––––––––––––––––––––––––––+")
